name: Cypress Pokemon Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress/cypress.config.js
      
      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30

      #- name: Cypress.io
      #  uses: cypress-io/github-action@v2
      #  with:
      #    browser: electron
      #    command: npx cypress run --config-file cypress.config.js
