name: Cypress Pokemon Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          headless: true
          browser: electron
          command: npx cypress run --config-file cypress.config.js
        
